### ISSUE TITLE
Advanpix conflict

### ISSUE THREAD

**Issue by edoktay** [katlund/BlockStab#18]
After the addition of unit_tests.m, Advanpix started to conflict with Matlab built-in functions also available in Advanpix. The conflict also causes to block the user from opening any file in Matlab until restarting the program.

**Comment by katlund** [comment]
See comment on https://github.com/katlund/BlockStab/commit/fb3ba9502b6fe1da800d233c965e56f326d7af10 .

We'll assume this is fixed for now, but since we don't really understand why, we should keep an eye out, in case it happens again.
